<a href="https://colab.research.google.com/github/fhsmartins/MBA/blob/main/Aula01/Python_Exercicios_fixacao_solucoes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color="red"> MBA em IA e Big Data</font>
## <span style="color:red">Linguagens e Ferramentas para Inteligência Artificial e Big Data (Python e SQL)</span>

### <span style="color:darkred">Python: referências, operações e funções</span>

*Leandro Franco de Souza*<br>
*ICMC/USP São Carlos*

*(com material dos Profs. Luis Gustavo Nonato & Moacir Antonelli Ponti)*

# <span style="color:red">Solução dos exercícios de fixação.</span>

### Exercício 1)

Qual o tipo do valor resultante das operações abaixo (ou das variáveis as quais foram atribuídos)?

a) `False + True`<br>
b) `2 * 1e2**2`<br>
c) `a = 6/2`<br>
d) `x = 6//2 + 6%2`<br>
e) `(2 + 4) == 4 or 0 <= 1`<br>

In [ ]:
print(False+True, type(False+True))

1 <class 'int'>


In [ ]:
print(2 * 1e2**2, type(2 * 1e2**2))

20000.0 <class 'float'>


In [ ]:
a = 6/2
print(a, type(a))

3.0 <class 'float'>


In [ ]:
x = 6//2 + 6%2
print(x, type(x))

3 <class 'int'>


In [ ]:
print((2 + 4) == 4 or 0 <= 1, type((2 + 4) == 4 or 0 <= 1))

True <class 'bool'>


### Exercício 2)

Crie uma variável contendo um ano (um valor inteiro entre 0 e 3000)

A seguir, se o ano for divisível por 4, exiba na tela 'Pode ser um ano bissexto'; caso contrário exiba 'Definitivamente não é um ano bissexto'

__Dica:__ Utilize o operador `%` que retorna o resto da divisão de um número por outro.

In [ ]:
ano = 2021
if (ano % 4 == 0):
    print('Pode ser um ano bissexto')
else:
    print('Definitivamente não é um ano bissexto')

Definitivamente não é um ano bissexto


### Exercício 3)

Dada a lista `valores` abaixo, crie uma nova lista chamada `numeros` contendo apenas elementos `float` ou `int`.

Note que essa nova lista pode ter menos elementos do que a lista existente.

Ao final exiba a nova lista `numeros`

__Dica__: Percorra a lista com uma estrutura de repetição e utilize `type()` para retornar o tipo e compare com o desejado. Exemplo:
```python
type(3) == int
```
Retorna `True`

In [ ]:
valores = ['três', 56, 342, 12.4e-5, 4+3j, ('A', 1, 50.1), -0.19e4, 1000, 960, -406]

In [ ]:
numeros = []
for i in valores:
    if (type(i) == float or type(i) == int):
        numeros.append(i)

print(numeros)

[56, 342, 0.000124, -1900.0, 1000, 960, -406]


### Exercício 4)

Escreva uma **função** que receba por parâmetro uma taxa de juros pagas ao ano, calcule e retorne um número inteiro relativo a quantos anos serão necessários para que um investimento nessa taxa dobre de valor. Assuma juros compostos e use uma estrutura de repetição para calcular.


In [ ]:
def dobrar_investimento(juros):
    valor = 1
    anos = 0
    while (valor < 2):
        anos += 1
        valor = valor*(1+juros)
    return anos

a5 = dobrar_investimento(0.05)
print(a5)

a7 = dobrar_investimento(0.07)
print(a7)

15
11


### Exercício 5)
Considere a lista `linguagens` declarada abaixo.
- Utilizando fatiamento, imprima o subconjunto de elementos entre o segundo e o quarto elemento (inclusive)
- Gere uma nova lista chamada `maiores4` contendo os elementos da lista `linguagens` que possuam quatro caracteres ou mais, utilizando a função `len()`.
- Gere uma nova lista chamada `j_ou_c` contendo os elementos da lista `linguagens` que começam com a letra 'j' ou com a letra 'c'.

In [ ]:
linguagens = ['python', 'java', 'c++', 'javascript', 'c#', 'go', 'r', 'cobol', 'ruby', 'lisp']

print(linguagens[1:5])

quatro_ou_mais = []
for elemento in linguagens:
    if len(elemento) >= 4:
        quatro_ou_mais.append(elemento)

j_ou_c = []
for elemento in linguagens:
    if elemento[0] == 'j':
        j_ou_c.append(elemento)
    if elemento[0] == 'c':
        j_ou_c.append(elemento)

print("Quatro ou mais: ", quatro_ou_mais)
print("Inicia com j ou c: ", j_ou_c)

['java', 'c++', 'javascript', 'c#']
Quatro ou mais:  ['python', 'java', 'javascript', 'cobol', 'ruby', 'lisp']
Inicia com j ou c:  ['java', 'c++', 'javascript', 'c#', 'cobol']


### Exercício 6)

Codifique uma função `conta_palavras()` que, a partir de um um texto (string) contendo palavras separadas por vírgulas apenas - considere que não há outras pontuações:
1. Inicie criando uma lista de palavras e
2. Use um dicionário para contar a frequência de cada palavra no texto, retornando o dicionário obtido.

*Dica: use a função `str.split()` para separar uma string em substrings usando como delimitador um caracter especificado por argumento*

Exemplo:

```
nomes = "ana,fábio,cristina,ana,fábio,ubiratã,ana"
freq = conta_palavras(nomes)
print(freq)
```
Deve gerar:
```
{'ana': 3, 'fábio': 2, 'cristina': 1, 'ubiratã': 1}
```

In [ ]:
def conta_palavras(frase):
    pals = frase.split(',')
    freq = {}

    for p in pals:
        if p not in freq:
            freq[p] = 1
        else:
            freq[p] += 1

    return freq

nomes = "ana,fábio,cristina,ana,fábio,ubiratã,ana"
freq = conta_palavras(nomes)
print(freq)

{'ana': 3, 'fábio': 2, 'cristina': 1, 'ubiratã': 1}


### Exercício 7)
Considere a lista `produtos` definida abaixo, onde cada elemento é uma tupla possuindo:
* elemento 1: o nome de um produto
* elemento 2: e uma lista de preços encontradas no mercado.

Calcule a média de preços de cada produto, salvando o resultado em uma nova lista chamada `preco_medio`.

Posteriormente, sorteie um dos produtos e exiba na tela o nome e preço médio desse produto sorteado

__Dica:__ Utilize a função `fsum()` do módulo `math` para somar os valores daa lista. Por exemplo:
```python
ls = [1.0,1.0,1.0,1.0,1.0]
print(fsum(ls))
```
resulta no valor 5

In [ ]:
produtos = [('soja', [170.1, 183.0, 175.0]),
            ('algodao', [143.4]),
            ('cacau', [199, 185.1]),
            ('café', [880, 750.9, 795.1, 900])]

In [ ]:
from math import fsum
from random import randint

preco_medio = []
for p in produtos:
    media = fsum(p[1])/len(p[1])
    preco_medio.append(media)

sorteio = randint(0,len(produtos)-1)
print(produtos[sorteio][0], "preço médio=", preco_medio[sorteio])

soja preço médio= 176.03333333333333


Os exercícios a seguir farão uso do arquivo <font style="font-family: monaco">WorldCups.csv</font>

O arquivo <font style="font-family: monaco">WorldCups.csv</font> possui as seguintes colunas:
- Year: ano da copa
- Country: pais sede
- Winner: campeão
- RunnersUp: disputou a final com o campeão
- Third: terceiro colocado
- Fourth: quarto colocado
- GoalsScored: número de gols na copa
- QualifiedTeams: número de times que disputaram a copa
- MatchesPlayed: número de jogos
- Attendance: número de espectadores (público)

### Exercício 8)
Utilizando o <font color='blue'>pandas</font> leia o arquivo <font style="font-family: monaco">WorldCups.csv</font> como DataFrame.
- Definina a coluna 'Year' como índice
- Exiba as 5 primeiras linhas do DataFrame
- Exiba o tipo de dado de cada coluna
- Imprima o número de linhas do DataFrame

In [ ]:
# SOLUÇÃO
# Voce precisa colocar o caminho do diretório no drive onde o
# arquivo WorldCups.csv está

import pandas as pd
df = pd.read_csv('WorldCups.csv')

In [ ]:
df.set_index('Year', inplace=True)

In [ ]:
df.head()

Country      Winner       RunnersUp    Third      Fourth  \
Year                                                                 
1930      Uruguay     Uruguay       Argentina      USA  Yugoslavia   
1934        Italy       Italy  Czechoslovakia  Germany     Austria   
1938       France       Italy         Hungary   Brazil      Sweden   
1950       Brazil     Uruguay          Brazil   Sweden       Spain   
1954  Switzerland  Germany FR         Hungary  Austria     Uruguay   

      GoalsScored  QualifiedTeams  MatchesPlayed  Attendance  
Year                                                          
1930           70              13             18      590549  
1934           70              16             17      363000  
1938           84              15             18      375700  
1950           88              13             22     1045246  
1954          140              16             26      768607

In [ ]:
print(df.dtypes)

Country           object
Winner            object
RunnersUp         object
Third             object
Fourth            object
GoalsScored        int64
QualifiedTeams     int64
MatchesPlayed      int64
Attendance         int64
dtype: object


In [ ]:
print("Número de linhas = ", df.shape[0])

Número de linhas =  20


### Exercício 9)
Remova as colunas 'QualifiedTeams' e 'Fourth' do DataFrame.

A seguir, com o DataFrame resultante, exiba os vencedores das copas entre os anos 1954 e 1982 (inclusive)

In [ ]:
df = df.drop(['QualifiedTeams','Fourth'],axis=1)

In [ ]:
df.loc[1954:1982,'Winner']

Year
1954    Germany FR
1958        Brazil
1962        Brazil
1966       England
1970        Brazil
1974    Germany FR
1978     Argentina
1982         Italy
Name: Winner, dtype: object

### Exercício 10)

Crie uma nova coluna com a média de gols por partida chamada `AverageGoalsMatch`, dividindo o número de gols pelo número de partidas jogadas.

A seguir, encontre e/ou calcule:
- os anos em que o Brasil ganhou a copa, armazene em uma lista as média de gols naqueles anos. A seguir imprima a lista na tela.
- os anos em que o Brasil jogou uma final (os finalistas estão nas colunas 'Winner' e 'RunnersUp') e imprima na tela os anos e a média de gols de cada ano
- a porcentagem de vitórias do Brasil em finais, e imprima na tela

In [ ]:
df['AverageGoalsMatch'] = df['GoalsScored']/df['MatchesPlayed']
df

Country      Winner       RunnersUp        Third  GoalsScored  \
Year                                                                       
1930       Uruguay     Uruguay       Argentina          USA           70   
1934         Italy       Italy  Czechoslovakia      Germany           70   
1938        France       Italy         Hungary       Brazil           84   
1950        Brazil     Uruguay          Brazil       Sweden           88   
1954   Switzerland  Germany FR         Hungary      Austria          140   
1958        Sweden      Brazil          Sweden       France          126   
1962         Chile      Brazil  Czechoslovakia        Chile           89   
1966       England     England      Germany FR     Portugal           89   
1970        Mexico      Brazil           Italy   Germany FR           95   
1974       Germany  Germany FR     Netherlands       Poland           97   
1978     Argentina   Argentina     Netherlands       Brazil          102   
1982         Spain       Italy      Germany FR       Poland          146   
1986        Mexico   Argentina      Germany FR       France          132   
1990         Italy  Germany FR       Argentina        Italy          115   
1994           USA      Brazil           Italy       Sweden          141   
1998        France      France          Brazil      Croatia          171   
2002   Korea/Japan      Brazil         Germany       Turkey          161   
2006       Germany       Italy          France      Germany          147   
2010  South Africa       Spain     Netherlands      Germany          145   
2014        Brazil     Germany       Argentina  Netherlands          171   

      MatchesPlayed  Attendance  AverageGoalsMatch  
Year                                                
1930             18      590549           3.888889  
1934             17      363000           4.117647  
1938             18      375700           4.666667  
1950             22     1045246           4.000000  
1954             26      768607           5.384615  
1958             35      819810           3.600000  
1962             32      893172           2.781250  
1966             32     1563135           2.781250  
1970             32     1603975           2.968750  
1974             38     1865753           2.552632  
1978             38     1545791           2.684211  
1982             52     2109723           2.807692  
1986             52     2394031           2.538462  
1990             52     2516215           2.211538  
1994             52     3587538           2.711538  
1998             64     2785100           2.671875  
2002             64     2705197           2.515625  
2006             64     3359439           2.296875  
2010             64     3178856           2.265625  
2014             64     3386810           2.671875

In [ ]:
# query para buscar vencedor igual a Brazil
# poderia também ter sido feito com loc ou iloc
ganhou = df.query('Winner == "Brazil"')
participou = df.query('Winner == "Brazil" | RunnersUp == "Brazil"')

In [ ]:
ganhou

Country  Winner       RunnersUp       Third  GoalsScored  \
Year                                                                 
1958       Sweden  Brazil          Sweden      France          126   
1962        Chile  Brazil  Czechoslovakia       Chile           89   
1970       Mexico  Brazil           Italy  Germany FR           95   
1994          USA  Brazil           Italy      Sweden          141   
2002  Korea/Japan  Brazil         Germany      Turkey          161   

      MatchesPlayed  Attendance  AverageGoalsMatch  
Year                                                
1958             35      819810           3.600000  
1962             32      893172           2.781250  
1970             32     1603975           2.968750  
1994             52     3587538           2.711538  
2002             64     2705197           2.515625

In [ ]:
# para verificar somente os anos, olhamos somente os rótulos dos DataFrames acima
lista_media_gols = list(ganhou['AverageGoalsMatch'].values)
print('média de gols nos anos que ganhou:', lista_media_gols)    # anos em que o Brasil venceu

print('\nanos em que foi para a final e média de gols:')
print(participou['AverageGoalsMatch']) # anos em que o Brasil disputou uma final

# basta dividimos o número de disputas de final pelo número de vitórias
print('\nporcentagem de vitórias em finais:', round((ganhou.shape[0] / participou.shape[0])*100,1), '%')

média de gols nos anos que ganhou: [3.6, 2.78125, 2.96875, 2.7115384615384617, 2.515625]

anos em que foi para a final e média de gols:
Year
1950    4.000000
1958    3.600000
1962    2.781250
1970    2.968750
1994    2.711538
1998    2.671875
2002    2.515625
Name: AverageGoalsMatch, dtype: float64

porcentagem de vitórias em finais: 71.4 %


### Exercício 11)

Codifique uma função que use comprehension para retornar uma lista com `n` valores numéricos iniciando em 0 e  com passo `p` permitindo um número float como passo. Arredonde cada número para 5 casas decimais usando a função `round(,5)`

Exemplo para n=8, p=0.05
```
[0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]
```

In [ ]:
def frange(n,p):
    lista = [round(x*p,5) for x in range(n+1)]
    return lista

lista = frange(8,0.05)
print(len(lista))
print(lista)

9
[0.0, 0.05, 0.1, 0.15, 0.2, 0.25, 0.3, 0.35, 0.4]


### Exercício 12)

A partir de um vetor com números inteiros aleatórios, calcular seu `log` e criar uma lista com o resultado.
* se o número for 0 substituir o valor por `nan` (not a number) da biblioteca `math` para indicar que o resultado não é numérico

In [ ]:
import random as rd

n = 25
rand_num = [rd.randint(0,10) for _ in range(n)]
print(rand_num)

[3, 3, 9, 7, 6, 9, 1, 0, 9, 2, 8, 4, 9, 6, 10, 0, 0, 6, 8, 5, 8, 2, 8, 0, 9]


In [ ]:
from math import nan, log
log_num = [log(x) if x != 0 else nan for x in rand_num]
print(log_num)

[1.0986122886681098, 1.0986122886681098, 2.1972245773362196, 1.9459101490553132, 1.791759469228055, 2.1972245773362196, 0.0, nan, 2.1972245773362196, 0.6931471805599453, 2.0794415416798357, 1.3862943611198906, 2.1972245773362196, 1.791759469228055, 2.302585092994046, nan, nan, 1.791759469228055, 2.0794415416798357, 1.6094379124341003, 2.0794415416798357, 0.6931471805599453, 2.0794415416798357, nan, 2.1972245773362196]


### Exercício 13)


Codifique uma função que receba como argumento duas listas de números com o mesmo tamanho. Use comprehension para retornar uma nova lista que é a multiplicação elemento-a-elemento das duas listas.  Caso as listas não possuam o mesmo tamanho emita uma mensagem de erro e retorne a constante `math.nan` do módulo `math`.

Exemplo:
```
l1 = [1, 2, 3, 4, 5]
l2 = [5, 5, 5, 10, 10]
multiplica_listas(l1,l2)

  [5, 10, 15, 40, 50]
```

In [ ]:
from math import nan
import sys

def multiplica_listas(l1,l2):
    if (len(l1) != len(l2)):
        print('Erro: Listas devem ter o mesmo tamanho', file=sys.stderr)
        return nan
    else:
        return [x*y for x,y in zip(l1,l2)]

In [ ]:
l1 = [1, 2, 3, 4, 5]
l2 = [5, 5, 5, 10, 10]

print(multiplica_listas(l1,l2))

l3 = [3, 4, 5]
print(multiplica_listas(l1,l3))

[5, 10, 15, 40, 50]
nan


Erro: Listas devem ter o mesmo tamanho


### Exercício 14)

Codifique uma comprehension que simule uma matriz de tamanho n x n, cujos elementos são dados por `(i+j*i)`, sendo `i` o índice da linha e `j` o índice da coluna. Para simular isso com uma lista de listas, o `i` corresponde ao índice da lista principal e o `j` aos índices das listas aninhadas.

Por exemplo, seja a segunda lista (posição i=1), o seu terceiro elemento (posição j=2) seria obtido por `1+2*1 = 3`

Exemplo com n = 3:
```
  [[0, 0, 0],
   [1, 2, 3],
   [2, 4, 6]]
```

In [ ]:
n = 3
matriz = [[i+j*i for j in range(n)] for i in range(n)]
print(matriz)

[[0, 0, 0], [1, 2, 3], [2, 4, 6]]


---

##  <font color="red">Solução do Desafio</font>

Temos uma série de pontos 3D organizados numa lista e gostaríamos de computar as distâncias entre todos os pontos pareados.

Calcular a distância entre dois pontos $p1 = (x_1,y_1,z_1)$ e  $p2 = (x_2,y_2,z_2)$ usando a fórmula

$$d(p1,p2) = |x_1 - x_2| +|y_1 - y_2| + |z_1 - z_2|,$$
em que $|.|$ representa o valor absoluto.

Exemplo com 2 pontos organizados em listas:
```
[[1.0, 1.0, 1.0],
 [3.0, 3.0, 3.0]]
```

A saída deve ser:
```
[[0.0, 6.0],
 [6.0, 0.0]]
```

Note que a diagonal principal tem sempre valor zero já que representa a distância de um ponto para ele mesmo, e que a matriz é simétrica pois a distância entre dois pontos p1 e p2 é tal que: d(p1,p2) = d(p2,p1).

Para isso utilize uma única linha contendo comprehensions aninhadas e com iteração em paralelo

In [ ]:
from math import fabs, fsum

pontos3d = [ [1.0, 1.0, 1.0],
             [0.0, 1.0, 3.0],
             [2.0, 2.0, 2.0],
             [0.0, 0.0, 0.0] ]

dists = [[fsum([fabs(a-b) for a,b in zip(p1,p2)]) for p2 in pontos3d] for p1 in pontos3d ]

for linha in dists:
    print(linha)

[0.0, 3.0, 3.0, 3.0]
[3.0, 0.0, 4.0, 4.0]
[3.0, 4.0, 0.0, 6.0]
[3.0, 4.0, 6.0, 0.0]


### Exercício 15)

Escreva uma expressão lambda que permita receber uma string contendo duas palavras relativas ao nome de uma pessoa e seu sobrenome. Essas são separadas por um ou mais espaços em branco. A expressão deve retornar o nome no formato: "SOBRENOME, N."

Exemplo:
```
nome = 'Dennis   ritchie'
```

Retorno:
```
RITCHIE, D.
```

A seguir escreva um comprehension que percorra uma lista contendo nomes e gere uma nova lista com os nomes no formato "SOBRENOME, N."

Exemplo:
```
nomes = ['Dennis   ritchie', 'ALAN  Turing', 'betty Holberton']
```

Retorno:
```
['RITCHIE, D.', 'TURING, A.', 'HOLBERTON, B.']
```

In [ ]:
f = lambda nome: nome.split()[-1].upper()+', '+nome.split()[0][0]+'.'
f('Moacir Ponti')

'PONTI, M.'

In [ ]:
cientistas_da_computacao = ['Betty Holberton', 'Alan Turing', 'Dennis Ritchie', 'Grace Hopper', 'Donald Knuth', 'Charles Babbage', 'Ada Lovelace', 'Geoffrey Hinton', 'Daphne Koller']
formato = [f(nome) for nome in cientistas_da_computacao]
print(formato)

['HOLBERTON, B.', 'TURING, A.', 'RITCHIE, D.', 'HOPPER, G.', 'KNUTH, D.', 'BABBAGE, C.', 'LOVELACE, A.', 'HINTON, G.', 'KOLLER, D.']


In [ ]:
f = lambda nome: nome.split()[-1].upper()+', '+nome.split()[0][0]+'.'
formato = [f(nome) for nome in cientistas_da_computacao]
for autor in formato:
    print(autor)

HOLBERTON, B.
TURING, A.
RITCHIE, D.
HOPPER, G.
KNUTH, D.
BABBAGE, C.
LOVELACE, A.
HINTON, G.
KOLLER, D.


### Exercício 16)

Dada uma lista de tuplas, em que cada tupla é formada por um par (str,list). Ver um exemplo abaixo.

```
l_tup = [('a',[8, 4, 6, 1]), ('b',[1, 2, 3, 4]), ('c',[5, 3, 3, 3])]
```
* Converta a lista de tuplas em um numpy array bidimensional em que cada lista é transformada em uma linha do array, ignorando a string.
* Percorra cada linha do array resultante usando `for`, exibindo na tela os 3 últimos elementos de cada array

Seu código deve funcionar para qualquer número de tuplas na lista, assuma que as listas tem sempre o mesmo número de elementos, todos numéricos.


In [ ]:
l_tup = [('a',[8, 4, 6, 1]), ('b',[1, 2, 3, 4]), ('c',[5, 3, 3, 3])]

In [ ]:
import numpy as np

arr = np.array([el[1] for el in l_tup])

for l in arr:
    print(l[-3:])

[4 6 1]
[2 3 4]
[3 3 3]


### Exercício 17)

Use o método `randint` do `numpy` para criar um array bidimensional com 6x10 elementos inteiros entre 1 e 5.

A seguir, considerando apenas a submatriz formada pelas linhas: 2 até 6 e as colunas 2, 5 e 8, copie para uma matriz unidimensional os valores maiores ou iguais a 4.

In [ ]:
x = np.random.randint(1,6,60).reshape(6,10)
print(x)

[[3 1 3 5 1 5 5 3 5 1]
 [3 5 1 2 4 5 4 4 5 1]
 [3 1 4 5 4 4 5 5 4 3]
 [3 1 4 4 2 4 4 5 5 1]
 [1 3 4 3 1 2 4 5 5 2]
 [2 2 1 1 4 3 3 1 5 2]]


In [ ]:
subx = x[2:,[2,5,8]]
vec = np.copy(subx[subx>=4])
print(vec)

[4 4 4 4 4 5 4 5 5]


### Exercício 18)


Dados dois arrays conforme abaixo que são notas (de 1 a 10) dadas a 4 diferentes serviços fornecidos por empresas concorrentes A e B. As notas de cada serviço estão organizadas nas 4 linhas dos arrays.

A empresa `A` coletou 10 notas, e `B` coletou 6 notas para cada serviço (simuladas aleatoriamente no código abaixo).

Os 4 serviços possuem pesos que é determinado pela lista `pesos` listada abaixo.

A empresa A deseja se comparar com a empresa B com base na média das notas da empresa B. Para isso:
1. usando redução, obtenha a média das notas de cada serviço da empresa B;
2. para cada serviço, calcule qual foi a menor nota observada por A considerando apenas as notas de A que foram maiores do que a média de B para aquele serviço;
3. armazene essas notas mínimas em um novo array de 4 elementos, e exiba esse array na tela;
4. utilizando multiplicação vetorial, calcule e exiba na tela a soma das notas mínimas ponderadas pelos pesos


In [ ]:
A = np.random.randint(low=1,high=11,size=(4,10))
B = np.random.randint(low=1,high=11,size=(4,6))
pesos = [0.15, 0.25, 0.3, 0.3]
print(A)
print(B)
print(pesos)

[[ 9  1  8  3  6  4  3  4  1  2]
 [ 7  5  5  4  7  7  6  2  5  6]
 [ 6  7  4  5  1  9  5  8  7  2]
 [ 5  5 10  4  4  2  2  2  3  4]]
[[ 6  4 10  1  4  3]
 [ 8  1  1 10 10  7]
 [ 3  7  9  1  5  9]
 [ 6  5  5  8  2  6]]
[0.15, 0.25, 0.3, 0.3]


In [ ]:
####
mins = []
for i,m in zip(range(B.shape[0]), np.mean(B,axis=1)):
    minv = np.min(A[i,:][A[i,:] > m])
    mins.append(minv)

mins = np.array(mins)
pesos = np.array(pesos)
print('1) Medias de B:', np.round(np.mean(B,axis=1),2))
print('2/3) Menores notas de A > do que medias de B:', mins)
print('  pesos=', pesos)
print('4) Soma ponderada:', np.round(mins.dot(pesos),2))


1) Medias de B: [4.67 6.17 5.67 5.33]
2/3) Menores notas de A > do que medias de B: [ 6  7  6 10]
  pesos= [0.15 0.25 0.3  0.3 ]
4) Soma ponderada: 7.45


### Exercício 19)

Carregue o arquivo `tips.csv`:
1. Filtre as linhas selecionando apenas jantares (time = 'Dinner') e cuja conta foi superior a 40 (total_bill > 40), mostrando o total da conta, número de pessoas na mesa e gorjeta (total_bill, size, tip);
2. Obtenha um novo dataframe em que seja mostrada a gorjeta (tip) média e máxima para cada valor de dia da semana (day) e horário (time)

In [ ]:
import pandas as pd

dtips = pd.read_csv('tips.csv')

print(dtips.loc[(dtips['time']=='Dinner') & (dtips['total_bill']>40),
          ['total_bill', 'size', 'tip'] ])

avgtip = dtips.groupby(['day','time'])['tip'].agg([np.mean, np.max])
print(avgtip)

     total_bill  size    tip
59        48.27     4   6.73
95        40.17     4   4.73
102       44.30     3   2.50
156       48.17     6   5.00
170       50.81     3  10.00
182       45.35     3   3.50
184       40.55     2   3.00
211       48.33     4   9.00
                 mean   amax
day  time                   
Fri  Dinner  2.940000   4.73
     Lunch   2.282500   3.48
Sat  Dinner  3.019647  10.00
Sun  Dinner  3.255132   6.50
Thur Dinner  3.000000   3.00
     Lunch   2.780500   6.70


### Exercício 20)

Carregue os arquivos `sales1.csv`, `sales1_shipdate.csv`  e `sales2.csv`, os quais possuem informações de vendas realizadas. Devemos juntar as bases de dados e tratá-las.

O arquivo `sales1_shipdate.csv` contém as datas de envio das ordens na `sales1.csv`. Já `sales2.csv` contém essa coluna no próprio arquivo

Para isso:

1. Combine as bases de dados, consolidando-as em um único DataFrame
2. Exiba na tela quais atributos possuem dados faltantes após a concatenação
    * Sabendo que `Total Revenue` é a multiplicação do preço unitário pela quantidade de unidades, preencha os valores faltantes dessa coluna
3. Detecte linhas duplicadas. Remova duplicatas, mantendo a primeira ocorrência, e imprima na tela quantas linhas foram removidas

In [ ]:
import pandas as pd
import numpy as np

s1 = pd.read_csv('sales1.csv')
s1_ship = pd.read_csv('sales1_shipdate.csv')
s2 = pd.read_csv('sales2.csv')

## 1 - Combinar as bases de dados

# juntar data do envio pelo Order ID
s1 = pd.merge(s1,s1_ship,on='Order ID',how='outer')
# concatenar os dois DataFrames
sales = pd.concat([s1,s2],axis=0)

sales.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102 entries, 0 to 87
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Country         102 non-null    object 
 1   Item Type       102 non-null    object 
 2   Online          93 non-null     float64
 3   Order Priority  102 non-null    object 
 4   Order Date      102 non-null    object 
 5   Order ID        102 non-null    int64  
 6   Units Sold      102 non-null    int64  
 7   Unit Price      102 non-null    float64
 8   Total Cost      102 non-null    float64
 9   Total Profit    102 non-null    float64
 10  Ship Date       100 non-null    object 
 11  Total Revenue   88 non-null     float64
dtypes: float64(5), int64(2), object(5)
memory usage: 10.4+ KB


In [ ]:
## 2 - Atributos com dados faltantes

for (colName, colData) in sales.items():
    if (np.any(pd.isna(colData))):
        print(colName)

Online
Ship Date
Total Revenue


In [ ]:
ind_falt = sales['Total Revenue'].isna()
print(sales.loc[ind_falt])

                  Country        Item Type  Online Order Priority Order Date  \
0                  Tuvalu        Baby Food     0.0              H  5/28/2010   
1                  Brazil           Cereal     1.0              C  8/22/2012   
2                  Russia  Office Supplies     0.0              L   5/2/2014   
3   Sao Tome and Principe           Fruits     1.0              C  6/20/2014   
4                  Rwanda  Office Supplies     0.0              L   2/1/2013   
5         Solomon Islands        Baby Food     1.0              C   2/4/2015   
6                  Angola        Household     0.0              M  4/23/2011   
7            Burkina Faso       Vegetables     1.0              H  7/17/2012   
8   Republic of the Congo    Personal Care     0.0              M  7/14/2015   
9                 Senegal           Cereal     1.0              H  4/18/2014   
10             Kyrgyzstan       Vegetables     1.0              H  6/24/2011   
11             Cape Verde          Cloth

In [ ]:
sales.loc[ind_falt, 'Total Revenue'] = sales.loc[ind_falt].apply(lambda x: x['Units Sold']*x['Unit Price'], axis=1)
print(sales.loc[ind_falt])

                  Country        Item Type  Online Order Priority Order Date  \
0                  Tuvalu        Baby Food     0.0              H  5/28/2010   
1                  Brazil           Cereal     1.0              C  8/22/2012   
2                  Russia  Office Supplies     0.0              L   5/2/2014   
3   Sao Tome and Principe           Fruits     1.0              C  6/20/2014   
4                  Rwanda  Office Supplies     0.0              L   2/1/2013   
5         Solomon Islands        Baby Food     1.0              C   2/4/2015   
6                  Angola        Household     0.0              M  4/23/2011   
7            Burkina Faso       Vegetables     1.0              H  7/17/2012   
8   Republic of the Congo    Personal Care     0.0              M  7/14/2015   
9                 Senegal           Cereal     1.0              H  4/18/2014   
10             Kyrgyzstan       Vegetables     1.0              H  6/24/2011   
11             Cape Verde          Cloth

In [ ]:
for (colName, colData) in sales.items():
    if (np.any(pd.isna(colData))):
        print(colName)

Online
Ship Date


In [ ]:
## 3 - Tratamento de duplicatas
print(sales[sales.duplicated(keep=False)])

print(sales.shape)
sales = sales.drop_duplicates(keep='first')
print(sales.shape)